apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-custom-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-retain-sc
  resources:
    requests:
      storage: 5Gi

